Full job

diff --git a/eng/pipelines/templates/jobs/archetype-sdk-client.yml b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
--- a/eng/pipelines/templates/jobs/archetype-sdk-client.yml
+++ b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
@@ -227,163 +227,163 @@ parameters:
 
 jobs:
   - ${{ each matrixEntry in parameters.Matrix }}:
-    - job: Validate_${{ matrixEntry.key }}
-      steps:
-        - pwsh: Write-Host '${{ convertToJson(matrixEntry) }}'
-    # - job: Validate ${{ matrixEntry.key }}
-    #   condition: and(succeededOrFailed(), ne(variables['Skip.Test'], 'true'))
-
-    #   variables:
-    #     # Insert the items from the matrix entry into the variable
-    #     ${{ insert }}: ${{ matrixEntry.value }}
-    #     CMOCKA_XML_FILE: "%g-test-results.xml"
-    #     CMOCKA_MESSAGE_OUTPUT: "xml"
-
-    #   pool:
-    #     name: $(Pool)
-    #     vmImage: $(OSVmImage)
-
-    #   # The `container` field, if specified, must not be empty. Use a template
-    #   # expression to exclude if the build does not require a container.
-    #   ${{ if matrixEntry.value.Container }}:
-    #     container: ${{ matrixEntry.value.Container }}
-
+    # - job: Validate_${{ matrixEntry.key }}
     #   steps:
-    #   - checkout: self
-    #     submodules: recursive
+    #     - pwsh: Write-Host '${{ convertToJson(matrixEntry) }}'
+    - job: Validate_${{ matrixEntry.key }}
+      condition: and(succeededOrFailed(), ne(variables['Skip.Test'], 'true'))
 
-    #   - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
-    #     parameters:
-    #       AgentImage: $(OSVmImage)
+      variables:
+        # Insert the items from the matrix entry into the variable
+        ${{ insert }}: ${{ matrixEntry.value }}
+        CMOCKA_XML_FILE: "%g-test-results.xml"
+        CMOCKA_MESSAGE_OUTPUT: "xml"
 
-    #   # Install apt dependencies (if appropriate)
-    #   - bash: sudo apt install -y $(AptDependencies)
-    #     condition: ne(variables['AptDependencies'], '')
-    #     displayName: Install dependencies from apt
+      pool:
+        name: $(Pool)
+        vmImage: $(OSVmImage)
 
-    #   - template: /eng/pipelines/templates/steps/vcpkg.yml
-    #     parameters:
-    #       DependenciesVariableName: vcpkg.deps
+      # The `container` field, if specified, must not be empty. Use a template
+      # expression to exclude if the build does not require a container.
+      ${{ if matrixEntry.value.Container }}:
+        container: ${{ matrixEntry.value.Container }}
 
-    #   - script: |
-    #       dotnet tool install -g dotnet-reportgenerator-globaltool
-    #       dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
-    #     displayName: Install coverage tools
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+      steps:
+      - checkout: self
+        submodules: recursive
 
-    #   - template: /eng/pipelines/templates/steps/cmake-build.yml
-    #     parameters:
-    #       BuildArgs: $(build.args)
-    #       BuildType: $(BuildType)
+      - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
+        parameters:
+          AgentImage: $(OSVmImage)
 
-    #   # Run unit tests
-    #   - script: |
-    #       ctest -V
-    #     workingDirectory: build
-    #     displayName: ctest
+      # Install apt dependencies (if appropriate)
+      - bash: sudo apt install -y $(AptDependencies)
+        condition: ne(variables['AptDependencies'], '')
+        displayName: Install dependencies from apt
 
-    #   # Publish test results to Azure Pipelines
-    #   - task: PublishTestResults@2
-    #     inputs:
-    #       testResultsFormat: 'JUnit'
-    #       testResultsFiles: '**/*-test-results.xml'
-    #       mergeTestResults: true
-    #       testRunTitle: 'C99 - $(Agent.JobName)'
-    #     condition: contains(variables['vcpkg.deps'], 'cmocka')
+      - template: /eng/pipelines/templates/steps/vcpkg.yml
+        parameters:
+          DependenciesVariableName: vcpkg.deps
 
-    #   # Make coverage targets (specified in coverage_targets.txt) and assemble
-    #   # coverage report
-    #   - bash: |
-    #       make `cat coverage_targets.txt`
-    #       ../tools/reportgenerator "-reports:sdk/*/*/*/*cov_xml.xml" "-targetdir:." "-reporttypes:Cobertura"
-    #     workingDirectory: build
-    #     displayName: Generate Code Coverage Data
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+      - script: |
+          dotnet tool install -g dotnet-reportgenerator-globaltool
+          dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
+        displayName: Install coverage tools
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
-    #   - task: PublishCodeCoverageResults@1
-    #     inputs:
-    #         codeCoverageTool: Cobertura
-    #         summaryFileLocation: '$(Build.SourcesDirectory)/**/Cobertura.xml'
-    #     displayName: Publish Code Coverage to DevOps
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+      - template: /eng/pipelines/templates/steps/cmake-build.yml
+        parameters:
+          BuildArgs: $(build.args)
+          BuildType: $(BuildType)
+
+      # Run unit tests
+      - script: |
+          ctest -V
+        workingDirectory: build
+        displayName: ctest
+
+      # Publish test results to Azure Pipelines
+      - task: PublishTestResults@2
+        inputs:
+          testResultsFormat: 'JUnit'
+          testResultsFiles: '**/*-test-results.xml'
+          mergeTestResults: true
+          testRunTitle: 'C99 - $(Agent.JobName)'
+        condition: contains(variables['vcpkg.deps'], 'cmocka')
+
+      # Make coverage targets (specified in coverage_targets.txt) and assemble
+      # coverage report
+      - bash: |
+          make `cat coverage_targets.txt`
+          ../tools/reportgenerator "-reports:sdk/*/*/*/*cov_xml.xml" "-targetdir:." "-reporttypes:Cobertura"
+        workingDirectory: build
+        displayName: Generate Code Coverage Data
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+
+      - task: PublishCodeCoverageResults@1
+        inputs:
+            codeCoverageTool: Cobertura
+            summaryFileLocation: '$(Build.SourcesDirectory)/**/Cobertura.xml'
+        displayName: Publish Code Coverage to DevOps
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
 
-    #   - task: CopyFiles@2
-    #     inputs:
-    #       contents: "**/*.map"
-    #       targetFolder: $(Build.ArtifactStagingDirectory)
-    #       flattenFolders: true
-    #     condition: eq(variables['PublishMapFiles'], 'true')
+      - task: CopyFiles@2
+        inputs:
+          contents: "**/*.map"
+          targetFolder: $(Build.ArtifactStagingDirectory)
+          flattenFolders: true
+        condition: eq(variables['PublishMapFiles'], 'true')
 
-    #   - task: PublishPipelineArtifact@1
-    #     inputs:
-    #       artifactName: map-files-$(MapFileArtifactSuffix)
-    #       path: $(Build.ArtifactStagingDirectory)
-    #     condition: eq(variables['PublishMapFiles'], 'true')
+      - task: PublishPipelineArtifact@1
+        inputs:
+          artifactName: map-files-$(MapFileArtifactSuffix)
+          path: $(Build.ArtifactStagingDirectory)
+        condition: eq(variables['PublishMapFiles'], 'true')
 
-    #   - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
-    #     displayName: Check line coverage
-    #     inputs:
-    #       checkCoverage: true
-    #       coverageFailOption: fixed
-    #       coverageType: line
-    #       # 90% minimum line coverage
-    #       coverageThreshold: 90
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+      - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
+        displayName: Check line coverage
+        inputs:
+          checkCoverage: true
+          coverageFailOption: fixed
+          coverageType: line
+          # 90% minimum line coverage
+          coverageThreshold: 90
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
-    #   - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
-    #     displayName: Check branch coverage
-    #     inputs:
-    #       checkCoverage: true
-    #       coverageFailOption: fixed
-    #       coverageType: branch
-    #       # 70% minimum branch coverage
-    #       coverageThreshold: 70
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+      - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
+        displayName: Check branch coverage
+        inputs:
+          checkCoverage: true
+          coverageFailOption: fixed
+          coverageType: branch
+          # 70% minimum branch coverage
+          coverageThreshold: 70
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
-    #   # Validate all the files are saved as ASCII only without a UTF-8 BOM.
-    #   - bash: |
-    #       # Run grep recursive excluding git folder and known expected files and save a file with results.
-    #       grep -I -P -n "[^\x00-\x7F]" -r --exclude-dir ".git" --exclude-dir "docs" --exclude-dir "tools" --exclude "*CodeCoverage.cmake*" --exclude "grepResults" . > grepResults
+      # Validate all the files are saved as ASCII only without a UTF-8 BOM.
+      - bash: |
+          # Run grep recursive excluding git folder and known expected files and save a file with results.
+          grep -I -P -n "[^\x00-\x7F]" -r --exclude-dir ".git" --exclude-dir "docs" --exclude-dir "tools" --exclude "*CodeCoverage.cmake*" --exclude "grepResults" . > grepResults
 
-    #       # Display results to console.
-    #       cat grepResults
+          # Display results to console.
+          cat grepResults
 
-    #       # Each result will produce one line, count how many lines were found.
-    #       files_with_non_ascii=($(wc -l < grepResults))
+          # Each result will produce one line, count how many lines were found.
+          files_with_non_ascii=($(wc -l < grepResults))
 
-    #       # Show info about the total files that needs attention.
-    #       echo Files found with non-ASCII characters: $files_with_non_ascii
+          # Show info about the total files that needs attention.
+          echo Files found with non-ASCII characters: $files_with_non_ascii
           
-    #       # Remove the grepResults file.
-    #       rm grepResults
+          # Remove the grepResults file.
+          rm grepResults
 
-    #       # Return the count. When greater than 0, the step will fail.
-    #       exit $files_with_non_ascii
+          # Return the count. When greater than 0, the step will fail.
+          exit $files_with_non_ascii
 
-    #     displayName: Validate Characters are ASCII
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+        displayName: Validate Characters are ASCII
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
-    #   # Validate all the files are formatted correctly according to the .clang-format file.
-    #   - bash: |
-    #       # Run clang-format recursively on each source and header file within the repo.
-    #       clang-format --version
-    #       find . \( -iname '*.h' -o -iname '*.c' \) -exec clang-format -i {} \;
+      # Validate all the files are formatted correctly according to the .clang-format file.
+      - bash: |
+          # Run clang-format recursively on each source and header file within the repo.
+          clang-format --version
+          find . \( -iname '*.h' -o -iname '*.c' \) -exec clang-format -i {} \;
 
-    #       git status --untracked-files=no --porcelain
+          git status --untracked-files=no --porcelain
 
-    #       if [[ `git status --untracked-files=no --porcelain` ]]; then
-    #         echo Some files were not formatted correctly according to the .clang-format file.
-    #         echo Please run clang-format to fix the issue by using this bash command at the root of the repo:
-    #         echo "find . \( -iname '*.h' -o -iname '*.c' \) -exec clang-format -i {} \;"
-    #         exit 1
-    #       fi
+          if [[ `git status --untracked-files=no --porcelain` ]]; then
+            echo Some files were not formatted correctly according to the .clang-format file.
+            echo Please run clang-format to fix the issue by using this bash command at the root of the repo:
+            echo "find . \( -iname '*.h' -o -iname '*.c' \) -exec clang-format -i {} \;"
+            exit 1
+          fi
 
-    #       echo Success, all files are formatted correctly according to the .clang-format file.
-    #       exit 0
+          echo Success, all files are formatted correctly according to the .clang-format file.
+          exit 0
 
-    #     displayName: Validate Clang Format
-    #     condition: eq(variables['AZ_SDK_CODE_COV'], 1)
+        displayName: Validate Clang Format
+        condition: eq(variables['AZ_SDK_CODE_COV'], 1)
 
   - job: GenerateReleaseArtifacts
     pool:
